#include <ice/ice.idl>

module ice {
  struct GlobalSimulationObjective {
    MetricIdentifier metric_id; //@key
    float value;
    float jitterStep;    // 0 if no jitter
    float floor;         // 'hard stop' limit of the model 
    float ceil;          // 'hard stop' limit of the model
  };
  #pragma keylist GlobalSimulationObjective metric_id
  const string GlobalSimulationObjectiveTopic = "GlobalSimulationObjective";

  struct LocalSimulationObjective {
    UniqueDeviceIdentifier unique_device_identifier; //@key
    MetricIdentifier metric_id; //@key
    float value;
  };
  #pragma keylist LocalSimulationObjective unique_device_identifier metric_id
  const string LocalSimulationObjectiveTopic = "LocalSimulationObjective";
};
