
CREATE TABLE SCHEMA_INFO (
        VERSION INT);

CREATE TABLE VITAL_VALUES (
        DEVICE_ID VARCHAR(25),
        METRIC_ID VARCHAR(25),
        INSTANCE_ID INTEGER,
        TIME_TICK TIMESTAMP,
        PATIENT_ID VARCHAR(25),
        VITAL_VALUE DOUBLE
        );

CREATE TABLE OBSERVATION_VALUES (
        MD_ID VARCHAR(25),
        TIME_TICK TIMESTAMP,
        PATIENT_ID VARCHAR(25),
        OBSERVATION VARCHAR(255)
        );


