#ifndef  _POLYMORPHISM_IDL_
#define  _POLYMORPHISM_IDL_

/********************


// Elements of a numeric
/*************
**** TOP 
Class	MDC_ATTR_CLASS	OIDType
Name-Binding	MDC_ATTR_NAME_BINDING	OIDType
**** VMO
Type	MDC_ATTR_ID_TYPE	TYPE	M
Handle	MDC_ATTR_ID_HANDLE	HANDLE	M
Label-String	MDC_ATTR_ID_LABEL_STRING	OCTET STRING	O
Ext-Obj-Relations	MDC_ATTR_EXT_OBJ_RELATION	ExtObjRelationList	O
**** Metric
Metric-Specification	MDC_ATTR_METRIC_SPECN	MetricSpec	M
Max-Delay-Time	MDC_ATTR_DELAY_TIME_MAX	RelativeTime	O
Metric-Status	MDC_ATTR_METRIC_STAT	MetricStatus	O
Measurement-Status	MDC_ATTR_MSMT_STAT	MeasurementStatus	O
Metric-Id-Partition	MDC_ATTR_METRIC_ID_PART	NomPartition	O
Metric-Id	MDC_ATTR_ID_PHYSIO	OIDType	O
Metric-Id-Ext	MDC_ATTR_ID_MSMT_EXT	ExtNomenRef	O
Unit-Code	MDC_ATTR_UNIT_CODE	OIDType	O
Unit-LabelString	MDC_ATTR_UNIT_LABEL_STRING	OCTET STRING	O
Vmo-Source-List	MDC_ATTR_VMO_LIST_SRC	VmoSourceList	O
Metric-Source-List	MDC_ATTR_METRIC_LIST_SRC	MetricSourceList	O
Msmt-Site-List	MDC_ATTR_SITE_LIST_MSMT	SiteList	O
Msmt-Site-List-Ext	MDC_ATTR_SITE_LIST_MSMT_EXT	SiteListExt	O
Body-Site-List	MDC_ATTR_SITE_LIST_BODY	SiteList	O
Body-Site-List-Ext	MDC_ATTR_SITE_LIST_BODY_EXT	SiteListExt	O
Metric-Calibration	MDC_ATTR_METRIC_CALIB	MetricCalibration	O
Color	MDC_ATTR_COLOR	SimpleColour	O
Measure-Mode	MDC_ATTR_MODE_MSMT	PrivateOid	O
Measure-Period	MDC_ATTR_TIME_PD_MSMT	MetricMeasure	O
Averaging-Period	MDC_ATTR_TIME_PD_AVG	MetricMeasure	O
Start-Time	MDC_ATTR_TIME_START	AbsoluteTime	O
Stop-Time	MDC_ATTR_TIME_STOP	AbsoluteTime	O
Metric-Info-LabelString	MDC_ATTR_METRIC_INFO_LABEL_STRING	OCTET STRING	O
Substance	MDC_ATTR_ID_SUBSTANCE	ExtNomenRef	O
Substance-Label-String	MDC_ATTR_ID_SUBSTANCE_LABEL_STRING	OCTET string
***** Numeric
Nu-Observed-Value	MDC_ATTR_NU_VAL_OBS	NuObsValue	C
Compound-Nu-Observed-Value	MDC_ATTR_NU_CMPD_VAL_OBS	NuObsValueCmp	C
Absolute-Time-Stamp	MDC_ATTR_TIME_STAMP_ABS	AbsoluteTime	O
Relative-Time-Stamp	MDC_ATTR_TIME_STAMP_REL	RelativeTime	O
HiRes-Time-Stamp	MDC_ATTR_TIME_STAMP_REL_HI_RES	HighResRelativeTime	O
Nu-Measure-Range	MDC_ATTR_NU_RANGE_MSMT	AbsoluteRange	O
Nu-Physiological-Range	MDC_ATTR_NU_RANGE_PHYSIO	AbsoluteRange	O
Nu-Measure-Resolution	MDC_ATTR_NU_MSMT_RES	FLOAT-Type	O
Display-Resolution	MDC_ATTR_DISP_RES	DispResolution	O
Accuracy	MDC_ATTR_NU_ACCUR_MSMT	FLOAT-Type	O
**************/

module org {
	module mdpnp {
		module qmdi {
			module types {
				module polymorphism {
					typedef unsigned short INTU16;
					typedef INTU16 OIDType;

					valuetype Attribute {
					
					};

					/**
					 * Top object.
					 * The Top object is the common inheritance base for all objects in the DIM.
					 */
					valuetype DIMT_Top {
					  /// Define the ID of the class.
					  /// IDs come from the object-oriented nomenclature partition.
					  public OIDType  class_id; //@key
					
					  /// Define ID of Name Binding attribute, e.g., DIMHANDLE.
					  /// IDs come from the object-oriented nomenclature partition.
					  public OIDType  name_binding_id; //@key
					};
					
					typedef INTU16 NomPartition;
					
					struct TTYPE {
					  NomPartition partition;
					  OIDType code;
					}; //@top-level false
					
					typedef INTU16 DIMHANDLE;
					
					typedef string OCTET_STRING;
					
					struct AttributeValueAssertion {
						OIDType attribute_id;
						Attribute attribute_value;
					};
					
					typedef sequence<AttributeValueAssertion> AttributeList;
					
					struct ExtObjRelationEntry {
						OIDType relation_type;
						OIDType related_object;
						AttributeList relation_attributes;
					};
					
					valuetype Foo : Attribute {
						public long fooValue;
					};
					
					valuetype Bar : Attribute {
						public string barValue;
					};
					
					typedef sequence<ExtObjRelationEntry> ExtObjRelationList;
					
					valuetype DIMT_VMO : DIMT_Top
					{
					  /// Define a specific static type of this object, as defined in the
					  /// object-oriented or metric nomenclature partition.
					  public TTYPE object_type; //@key
					
					  /// Locally unique short-hand identification.
					  public DIMHANDLE dimhandle; //@key
					
					  /// Text representation of type ID.
					  public OCTET_STRING label_string; 
					
					  public ExtObjRelationList ext_obj_relations;
					
					  
					}; 
				};
			};
		};
	};
};
#endif
