
/***
   This IDL is maintained for the sake of a unit test
   that demonstrates the performance implications of using
   strings in key fields in lieu of integers
***/

module org {
  module mdpnp {
    module types {
      module keysize {
        struct LargeStringKeys {
          // 128 bytes (single byte characters)
          string<128> unique_device_identifier; //@key
          // 64 bytes
          string<64> metric_id; //@key
          float value;
        };
        struct IntegerKeys {
          // 128 bytes (8 bytes * 16)
          long long unique_device_identifier[16]; //@key
          // 64 bytes (8 bytes * 8)
          long long metric_id[8]; //@key
          float value;
        };
      };
    };
  };
};

