
INSERT INTO PATIENT_INFO (MRN,LAST_NAME,FIRST_NAME,DOB,GENDER) VALUES  ('0x01','Patricia','Smith',   '1931-03-07', 'F');
INSERT INTO PATIENT_INFO (MRN,LAST_NAME,FIRST_NAME,DOB,GENDER) VALUES  ('0x02','Randall', 'Jones',   '1980-02-23', 'M');
INSERT INTO PATIENT_INFO (MRN,LAST_NAME,FIRST_NAME,DOB,GENDER) VALUES  ('0x03','John',    'Sullivan','1965-03-15', 'M');
INSERT INTO PATIENT_INFO (MRN,LAST_NAME,FIRST_NAME,DOB,GENDER) VALUES  ('0x04','Mary',    'Williams','1979-11-17', 'F');
