
CREATE TABLE SCHEMA_INFO (
        VERSION INT);

CREATE TABLE PATIENT_DEVICE_ASSOC (
        DEVICE_ID VARCHAR(25),
        PATIENT_ID VARCHAR(25));

CREATE TABLE PATIENT_INFO (
        MRN VARCHAR(25),
        LAST_NAME VARCHAR(25),
        FIRST_NAME VARCHAR(25),
        GENDER CHAR(1),
        DOB DATE);
