
CREATE TABLE PATIENT_DEVICE_ASSOC (
        DEVICE_ID VARCHAR(25),
        PATIENT_ID VARCHAR(25));

CREATE TABLE PATIENT_INFO (
        PATIENT_ID VARCHAR(25),
        DOB DATE,
        WEIGHT DOUBLE);
