
INSERT INTO PATIENT_INFO (MRN,LAST_NAME,FIRST_NAME,DOB,GENDER) VALUES  ('0x01','Homer',          'Simpson','1952-05-12', 'M');
INSERT INTO PATIENT_INFO (MRN,LAST_NAME,FIRST_NAME,DOB,GENDER) VALUES  ('0x02','Marge',          'Simpson','1954-03-19', 'F');
INSERT INTO PATIENT_INFO (MRN,LAST_NAME,FIRST_NAME,DOB,GENDER) VALUES  ('0x03','Bart',           'Simpson','1979-12-17', 'M');
INSERT INTO PATIENT_INFO (MRN,LAST_NAME,FIRST_NAME,DOB,GENDER) VALUES  ('0x04','Lisa',           'Simpson','1981-05-09', 'F');
INSERT INTO PATIENT_INFO (MRN,LAST_NAME,FIRST_NAME,DOB,GENDER) VALUES  ('0x05','Margaret Evelyn','Simpson','1988-11-17', 'F');

