
INSERT INTO PATIENT_INFO (PATIENT_ID) VALUES ('Homer');
INSERT INTO PATIENT_INFO (PATIENT_ID) VALUES ('Marge');
INSERT INTO PATIENT_INFO (PATIENT_ID) VALUES ('Bart');
INSERT INTO PATIENT_INFO (PATIENT_ID) VALUES ('Lisa');
INSERT INTO PATIENT_INFO (PATIENT_ID) VALUES ('Margaret Evelyn');

