#ifndef _SYSTEM_IDL_
#define _SYSTEM_IDL_

#include <org/mdpnp/types/normalized/types.idl>
#include <org/mdpnp/types/normalized/medical.idl>

module org {
  module mdpnp {
    module types {
      module normalized {
      
        struct Clock : Top {
        	long foo;
        };
      
        struct Battery : Top {
        	long foo;
        };
        
        struct Log : Top {
        	long foo;
        };
        
        struct EventLog : Log { 
        	long foo;
        };
      
        struct VirtualMedicalSystem : Top {
          	long foo;
        };
        
        struct MedicalDataSystem : VirtualMedicalSystem {
          sequence<Log> logs;
          sequence<Battery> batteries;
          sequence<Clock, 1> clock;
          sequence<VirtualMedicalDevice> virtualMedicalDevices;
        };
        
        struct SimpleMDS : MedicalDataSystem {
        	long foo;
        };
        
        struct HydraMDS : MedicalDataSystem {
        	long foo;
        };
        
        struct CompositeSingleBedMDS : MedicalDataSystem {
        	long foo;
        };
        
        struct CompositeMultiBedMDS : MedicalDataSystem {
        	long foo;
        };
      };
    };
  };
};

#endif