#ifndef _UNITS_IDL_
#define _UNITS_IDL_

module rosetta {
    const string DIM_MILLI_L = "DIM_MILLI_L";
    const string MDC_DIM_ANG_DEG = "MDC_DIM_ANG_DEG";
    const string MDC_DIM_ANG_RAD = "MDC_DIM_ANG_RAD";
    const string MDC_DIM_BEAT = "MDC_DIM_BEAT";
    const string MDC_DIM_BEAT_PER_MIN = "MDC_DIM_BEAT_PER_MIN";
    const string MDC_DIM_BEAT_PER_MIN_PER_X_L = "MDC_DIM_BEAT_PER_MIN_PER_X_L";
    const string MDC_DIM_BIT = "MDC_DIM_BIT";
    const string MDC_DIM_BOOLEAN = "MDC_DIM_BOOLEAN";
    const string MDC_DIM_BREATH = "MDC_DIM_BREATH";
    const string MDC_DIM_BREATHS_PER_MIN_PER_L = "MDC_DIM_BREATHS_PER_MIN_PER_L";
    const string MDC_DIM_BYTE = "MDC_DIM_BYTE";
    const string MDC_DIM_CELL = "MDC_DIM_CELL";
    const string MDC_DIM_CENTI_M = "MDC_DIM_CENTI_M";
    const string MDC_DIM_CM_H2O = "MDC_DIM_CM_H2O";
    const string MDC_DIM_CM_H2O_PER_L = "MDC_DIM_CM_H2O_PER_L";
    const string MDC_DIM_CM_H2O_PER_L_PER_SEC = "MDC_DIM_CM_H2O_PER_L_PER_SEC";
    const string MDC_DIM_CM_H2O_PER_PERCENT = "MDC_DIM_CM_H2O_PER_PERCENT";
    const string MDC_DIM_COUGH = "MDC_DIM_COUGH";
    const string MDC_DIM_CUBIC_X_L_PER_KG = "MDC_DIM_CUBIC_X_L_PER_KG";
    const string MDC_DIM_CUBIC_X_M = "MDC_DIM_CUBIC_X_M";
    const string MDC_DIM_CUBIC_X_M_PER_CM_CUBE = "MDC_DIM_CUBIC_X_M_PER_CM_CUBE";
    const string MDC_DIM_CUBIC_X_M_PER_DAY = "MDC_DIM_CUBIC_X_M_PER_DAY";
    const string MDC_DIM_CUBIC_X_M_PER_HR = "MDC_DIM_CUBIC_X_M_PER_HR";
    const string MDC_DIM_CUBIC_X_M_PER_M_CUBE = "MDC_DIM_CUBIC_X_M_PER_M_CUBE";
    const string MDC_DIM_CUBIC_X_M_PER_MIN = "MDC_DIM_CUBIC_X_M_PER_MIN";
    const string MDC_DIM_CUBIC_X_M_PER_SEC = "MDC_DIM_CUBIC_X_M_PER_SEC";
    const string MDC_DIM_DATE = "MDC_DIM_DATE";
    const string MDC_DIM_DAY = "MDC_DIM_DAY";
    const string MDC_DIM_DECI_BEL = "MDC_DIM_DECI_BEL";
    const string MDC_DIM_DECIBEL = "MDC_DIM_DECIBEL";
    const string MDC_DIM_DECIBEL_DECA_NV = "MDC_DIM_DECIBEL_DECA_NV";
    const string MDC_DIM_DECIBEL_X_MV = "MDC_DIM_DECIBEL_X_MV";
    const string MDC_DIM_DECIBEL_X_NV = "MDC_DIM_DECIBEL_X_NV";
    const string MDC_DIM_DECIBEL_X_UV = "MDC_DIM_DECIBEL_X_UV";
    const string MDC_DIM_DECIBEL_X_V = "MDC_DIM_DECIBEL_X_V";
    const string MDC_DIM_DEGC = "MDC_DIM_DEGC";
    const string MDC_DIM_DIMLESS = "MDC_DIM_DIMLESS";
    const string MDC_DIM_DROP = "MDC_DIM_DROP";
    const string MDC_DIM_DROPS_PER_MILLI_L = "MDC_DIM_DROPS_PER_MILLI_L";
    const string MDC_DIM_DROPS_PER_X_L = "MDC_DIM_DROPS_PER_X_L";
    const string MDC_DIM_DYNE_SEC_M_SQ_PER_CM_5 = "MDC_DIM_DYNE_SEC_M_SQ_PER_CM_5";
    const string MDC_DIM_DYNE_SEC_PER_CM_5 = "MDC_DIM_DYNE_SEC_PER_CM_5";
    const string MDC_DIM_DYNE_SEC_PER_CM5 = "MDC_DIM_DYNE_SEC_PER_CM5";
    const string MDC_DIM_DYNE_SEC_PER_M_SQ_PER_CM_5 = "MDC_DIM_DYNE_SEC_PER_M_SQ_PER_CM_5";
    const string MDC_DIM_EVOLT = "MDC_DIM_EVOLT";
    const string MDC_DIM_FAHR = "MDC_DIM_FAHR";
    const string MDC_DIM_G = "MDC_DIM_G";
    const string MDC_DIM_G_FORCE_M = "MDC_DIM_G_FORCE_M";
    const string MDC_DIM_G_M = "MDC_DIM_G_M";
    const string MDC_DIM_G_PER_DL = "MDC_DIM_G_PER_DL";
    const string MDC_DIM_G_PER_L = "MDC_DIM_G_PER_L";
    const string MDC_DIM_G_PER_ML = "MDC_DIM_G_PER_ML";
    const string MDC_DIM_HECTO_PASCAL = "MDC_DIM_HECTO_PASCAL";
    const string MDC_DIM_HR = "MDC_DIM_HR";
    const string MDC_DIM_HZ = "MDC_DIM_HZ";
    const string MDC_DIM_INCH = "MDC_DIM_INCH";
    const string MDC_DIM_INTL_UNIT_PER_ML = "MDC_DIM_INTL_UNIT_PER_ML";
    const string MDC_DIM_JOULES_PER_L = "MDC_DIM_JOULES_PER_L";
    const string MDC_DIM_KELVIN = "MDC_DIM_KELVIN";
    const string MDC_DIM_KELVIN_PER_X_WATT = "MDC_DIM_KELVIN_PER_X_WATT";
    const string MDC_DIM_KG_PER_M_SQ = "MDC_DIM_KG_PER_M_SQ#";
    const string MDC_DIM_KILO_CAL = "MDC_DIM_KILO_CAL";
    const string MDC_DIM_KILO_CAL_PER_DAY = "MDC_DIM_KILO_CAL_PER_DAY";
    const string MDC_DIM_KILO_G = "MDC_DIM_KILO_G";
    const string MDC_DIM_KILO_G_FORCE_M = "MDC_DIM_KILO_G_FORCE_M";
    const string MDC_DIM_KILO_G_FORCE_M_PER_L = "MDC_DIM_KILO_G_FORCE_M_PER_L";
    const string MDC_DIM_KILO_G_FORCE_M_PER_M_SQ = "MDC_DIM_KILO_G_FORCE_M_PER_M_SQ";
    const string MDC_DIM_KILO_G_PER_M_SQ = "MDC_DIM_KILO_G_PER_M_SQ";
    const string MDC_DIM_KILO_PASCAL = "MDC_DIM_KILO_PASCAL";
    const string MDC_DIM_L = "MDC_DIM_L";
    const string MDC_DIM_L_PER_MIN = "MDC_DIM_L_PER_MIN";
    const string MDC_DIM_L_PER_MIN_PER_M_SQ = "MDC_DIM_L_PER_MIN_PER_M_SQ";
    const string MDC_DIM_LB = "MDC_DIM_LB";
    const string MDC_DIM_MEGA_INTL_UNIT = "MDC_DIM_MEGA_INTL_UNIT";
    const string MDC_DIM_MEGA_INTL_UNIT_PER_DAY = "MDC_DIM_MEGA_INTL_UNIT_PER_DAY";
    const string MDC_DIM_MEGA_INTL_UNIT_PER_HR = "MDC_DIM_MEGA_INTL_UNIT_PER_HR";
    const string MDC_DIM_MEGA_INTL_UNIT_PER_KG = "MDC_DIM_MEGA_INTL_UNIT_PER_KG";
    const string MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_DAY = "MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_DAY";
    const string MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_HR = "MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_HR";
    const string MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_MIN = "MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_MIN";
    const string MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_SEC = "MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_SEC";
    const string MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ = "MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ";
    const string MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_DAY = "MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_DAY";
    const string MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_HR = "MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_HR";
    const string MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_MIN = "MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_MIN";
    const string MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_SEC = "MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_SEC";
    const string MDC_DIM_MEGA_INTL_UNIT_PER_MIN = "MDC_DIM_MEGA_INTL_UNIT_PER_MIN";
    const string MDC_DIM_MEGA_INTL_UNIT_PER_ML = "MDC_DIM_MEGA_INTL_UNIT_PER_ML";
    const string MDC_DIM_MEGA_INTL_UNIT_PER_SEC = "MDC_DIM_MEGA_INTL_UNIT_PER_SEC";
    const string MDC_DIM_MICRO_G = "MDC_DIM_MICRO_G";
    const string MDC_DIM_MICRO_G_PER_DAY = "MDC_DIM_MICRO_G_PER_DAY";
    const string MDC_DIM_MICRO_G_PER_HR = "MDC_DIM_MICRO_G_PER_HR";
    const string MDC_DIM_MICRO_G_PER_KG = "MDC_DIM_MICRO_G_PER_KG";
    const string MDC_DIM_MICRO_G_PER_KG_PER_DAY = "MDC_DIM_MICRO_G_PER_KG_PER_DAY";
    const string MDC_DIM_MICRO_G_PER_KG_PER_HR = "MDC_DIM_MICRO_G_PER_KG_PER_HR";
    const string MDC_DIM_MICRO_G_PER_KG_PER_MIN = "MDC_DIM_MICRO_G_PER_KG_PER_MIN";
    const string MDC_DIM_MICRO_G_PER_LB_PER_HR = "MDC_DIM_MICRO_G_PER_LB_PER_HR";
    const string MDC_DIM_MICRO_G_PER_LB_PER_MIN = "MDC_DIM_MICRO_G_PER_LB_PER_MIN";
    const string MDC_DIM_MICRO_G_PER_M_SQ = "MDC_DIM_MICRO_G_PER_M_SQ";
    const string MDC_DIM_MICRO_G_PER_M_SQ_PER_DAY = "MDC_DIM_MICRO_G_PER_M_SQ_PER_DAY";
    const string MDC_DIM_MICRO_G_PER_M_SQ_PER_HR = "MDC_DIM_MICRO_G_PER_M_SQ_PER_HR";
    const string MDC_DIM_MICRO_G_PER_M_SQ_PER_MIN = "MDC_DIM_MICRO_G_PER_M_SQ_PER_MIN";
    const string MDC_DIM_MICRO_G_PER_MIN = "MDC_DIM_MICRO_G_PER_MIN";
    const string MDC_DIM_MICRO_G_PER_ML = "MDC_DIM_MICRO_G_PER_ML";
    const string MDC_DIM_MICRO_INTL_UNIT_PER_KG = "MDC_DIM_MICRO_INTL_UNIT_PER_KG";
    const string MDC_DIM_MICRO_INTL_UNIT_PER_M_SQ = "MDC_DIM_MICRO_INTL_UNIT_PER_M_SQ";
    const string MDC_DIM_MICRO_L = "MDC_DIM_MICRO_L";
    const string MDC_DIM_MICRO_L_PER_MIN = "MDC_DIM_MICRO_L_PER_MIN";
    const string MDC_DIM_MICRO_M = "MDC_DIM_MICRO_M";
    const string MDC_DIM_MICRO_SEC = "MDC_DIM_MICRO_SEC";
    const string MDC_DIM_MICRO_VOLT = "MDC_DIM_MICRO_VOLT";
    const string MDC_DIM_MICRO_VOLT_PER_SEC = "MDC_DIM_MICRO_VOLT_PER_SEC";
    const string MDC_DIM_MICRO_WATT = "MDC_DIM_MICRO_WATT";
    const string MDC_DIM_MILLI_EQUIV = "MDC_DIM_MILLI_EQUIV";
    const string MDC_DIM_MILLI_EQUIV_PER_DAY = "MDC_DIM_MILLI_EQUIV_PER_DAY";
    const string MDC_DIM_MILLI_EQUIV_PER_HR = "MDC_DIM_MILLI_EQUIV_PER_HR";
    const string MDC_DIM_MILLI_EQUIV_PER_KG = "MDC_DIM_MILLI_EQUIV_PER_KG";
    const string MDC_DIM_MILLI_EQUIV_PER_KG_PER_DAY = "MDC_DIM_MILLI_EQUIV_PER_KG_PER_DAY";
    const string MDC_DIM_MILLI_EQUIV_PER_KG_PER_HR = "MDC_DIM_MILLI_EQUIV_PER_KG_PER_HR";
    const string MDC_DIM_MILLI_EQUIV_PER_KG_PER_MIN = "MDC_DIM_MILLI_EQUIV_PER_KG_PER_MIN";
    const string MDC_DIM_MILLI_EQUIV_PER_L = "MDC_DIM_MILLI_EQUIV_PER_L";
    const string MDC_DIM_MILLI_EQUIV_PER_LB_PER_HR = "MDC_DIM_MILLI_EQUIV_PER_LB_PER_HR";
    const string MDC_DIM_MILLI_EQUIV_PER_LB_PER_MIN = "MDC_DIM_MILLI_EQUIV_PER_LB_PER_MIN";
    const string MDC_DIM_MILLI_EQUIV_PER_M_SQ = "MDC_DIM_MILLI_EQUIV_PER_M_SQ";
    const string MDC_DIM_MILLI_EQUIV_PER_M_SQ_PER_DAY = "MDC_DIM_MILLI_EQUIV_PER_M_SQ_PER_DAY";
    const string MDC_DIM_MILLI_EQUIV_PER_M_SQ_PER_HR = "MDC_DIM_MILLI_EQUIV_PER_M_SQ_PER_HR";
    const string MDC_DIM_MILLI_EQUIV_PER_M_SQ_PER_MIN = "MDC_DIM_MILLI_EQUIV_PER_M_SQ_PER_MIN";
    const string MDC_DIM_MILLI_EQUIV_PER_MIN = "MDC_DIM_MILLI_EQUIV_PER_MIN";
    const string MDC_DIM_MILLI_EQUIV_PER_ML = "MDC_DIM_MILLI_EQUIV_PER_ML";
    const string MDC_DIM_MILLI_G = "MDC_DIM_MILLI_G";
    const string MDC_DIM_MILLI_G_PER_DAY = "MDC_DIM_MILLI_G_PER_DAY";
    const string MDC_DIM_MILLI_G_PER_DL = "MDC_DIM_MILLI_G_PER_DL";
    const string MDC_DIM_MILLI_G_PER_HR = "MDC_DIM_MILLI_G_PER_HR";
    const string MDC_DIM_MILLI_G_PER_KG = "MDC_DIM_MILLI_G_PER_KG";
    const string MDC_DIM_MILLI_G_PER_KG_PER_DAY = "MDC_DIM_MILLI_G_PER_KG_PER_DAY";
    const string MDC_DIM_MILLI_G_PER_KG_PER_HR = "MDC_DIM_MILLI_G_PER_KG_PER_HR";
    const string MDC_DIM_MILLI_G_PER_KG_PER_MIN = "MDC_DIM_MILLI_G_PER_KG_PER_MIN";
    const string MDC_DIM_MILLI_G_PER_LB_PER_HR = "MDC_DIM_MILLI_G_PER_LB_PER_HR";
    const string MDC_DIM_MILLI_G_PER_LB_PER_MIN = "MDC_DIM_MILLI_G_PER_LB_PER_MIN";
    const string MDC_DIM_MILLI_G_PER_M_SQ = "MDC_DIM_MILLI_G_PER_M_SQ";
    const string MDC_DIM_MILLI_G_PER_M_SQ_PER_DAY = "MDC_DIM_MILLI_G_PER_M_SQ_PER_DAY";
    const string MDC_DIM_MILLI_G_PER_M_SQ_PER_HR = "MDC_DIM_MILLI_G_PER_M_SQ_PER_HR";
    const string MDC_DIM_MILLI_G_PER_M_SQ_PER_MIN = "MDC_DIM_MILLI_G_PER_M_SQ_PER_MIN";
    const string MDC_DIM_MILLI_G_PER_MIN = "MDC_DIM_MILLI_G_PER_MIN";
    const string MDC_DIM_MILLI_G_PER_ML = "MDC_DIM_MILLI_G_PER_ML";
    const string MDC_DIM_MILLI_INTL_UNIT = "MDC_DIM_MILLI_INTL_UNIT";
    const string MDC_DIM_MILLI_INTL_UNIT_PER_DAY = "MDC_DIM_MILLI_INTL_UNIT_PER_DAY";
    const string MDC_DIM_MILLI_INTL_UNIT_PER_HR = "MDC_DIM_MILLI_INTL_UNIT_PER_HR";
    const string MDC_DIM_MILLI_INTL_UNIT_PER_KG = "MDC_DIM_MILLI_INTL_UNIT_PER_KG";
    const string MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_DAY = "MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_DAY";
    const string MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_HR = "MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_HR";
    const string MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_MIN = "MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_MIN";
    const string MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_SEC = "MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_SEC";
    const string MDC_DIM_MILLI_INTL_UNIT_PER_LB_PER_HR = "MDC_DIM_MILLI_INTL_UNIT_PER_LB_PER_HR";
    const string MDC_DIM_MILLI_INTL_UNIT_PER_LB_PER_MIN = "MDC_DIM_MILLI_INTL_UNIT_PER_LB_PER_MIN";
    const string MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ = "MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ";
    const string MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_DAY = "MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_DAY";
    const string MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_HR = "MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_HR";
    const string MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_MIN = "MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_MIN";
    const string MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_SEC = "MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_SEC";
    const string MDC_DIM_MILLI_INTL_UNIT_PER_MIN = "MDC_DIM_MILLI_INTL_UNIT_PER_MIN";
    const string MDC_DIM_MILLI_INTL_UNIT_PER_ML = "MDC_DIM_MILLI_INTL_UNIT_PER_ML";
    const string MDC_DIM_MILLI_L = "MDC_DIM_MILLI_L";
    const string MDC_DIM_MILLI_L_PER_BEAT = "MDC_DIM_MILLI_L_PER_BEAT";
    const string MDC_DIM_MILLI_L_PER_BREATH = "MDC_DIM_MILLI_L_PER_BREATH";
    const string MDC_DIM_MILLI_L_PER_CM_H2O = "MDC_DIM_MILLI_L_PER_CM_H2O";
    const string MDC_DIM_MILLI_L_PER_CM_H2O_PER_KG = "MDC_DIM_MILLI_L_PER_CM_H2O_PER_KG";
    const string MDC_DIM_MILLI_L_PER_DL = "MDC_DIM_MILLI_L_PER_DL";
    const string MDC_DIM_MILLI_L_PER_HR = "MDC_DIM_MILLI_L_PER_HR";
    const string MDC_DIM_MILLI_L_PER_KG = "MDC_DIM_MILLI_L_PER_KG";
    const string MDC_DIM_MILLI_L_PER_KG_PER_DAY = "MDC_DIM_MILLI_L_PER_KG_PER_DAY";
    const string MDC_DIM_MILLI_L_PER_KG_PER_HR = "MDC_DIM_MILLI_L_PER_KG_PER_HR";
    const string MDC_DIM_MILLI_L_PER_KG_PER_MIN = "MDC_DIM_MILLI_L_PER_KG_PER_MIN";
    const string MDC_DIM_MILLI_L_PER_M_SQ = "MDC_DIM_MILLI_L_PER_M_SQ";
    const string MDC_DIM_MILLI_L_PER_M_SQ_PER_DAY = "MDC_DIM_MILLI_L_PER_M_SQ_PER_DAY";
    const string MDC_DIM_MILLI_L_PER_M_SQ_PER_HR = "MDC_DIM_MILLI_L_PER_M_SQ_PER_HR";
    const string MDC_DIM_MILLI_L_PER_M_SQ_PER_MIN = "MDC_DIM_MILLI_L_PER_M_SQ_PER_MIN";
    const string MDC_DIM_MILLI_L_PER_MIN = "MDC_DIM_MILLI_L_PER_MIN";
    const string MDC_DIM_MILLI_L_PER_MIN_PER_KG = "MDC_DIM_MILLI_L_PER_MIN_PER_KG";
    const string MDC_DIM_MILLI_L_PER_MIN_PER_M_SQ = "MDC_DIM_MILLI_L_PER_MIN_PER_M_SQ";
    const string MDC_DIM_MILLI_M = "MDC_DIM_MILLI_M";
    const string MDC_DIM_MILLI_M_PER_SEC = "MDC_DIM_MILLI_M_PER_SEC";
    const string MDC_DIM_MILLI_MOLE = "MDC_DIM_MILLI_MOLE";
    const string MDC_DIM_MILLI_MOLE_PER_DAY = "MDC_DIM_MILLI_MOLE_PER_DAY";
    const string MDC_DIM_MILLI_MOLE_PER_HR = "MDC_DIM_MILLI_MOLE_PER_HR";
    const string MDC_DIM_MILLI_MOLE_PER_KG = "MDC_DIM_MILLI_MOLE_PER_KG";
    const string MDC_DIM_MILLI_MOLE_PER_KG_PER_DAY = "MDC_DIM_MILLI_MOLE_PER_KG_PER_DAY";
    const string MDC_DIM_MILLI_MOLE_PER_KG_PER_HR = "MDC_DIM_MILLI_MOLE_PER_KG_PER_HR";
    const string MDC_DIM_MILLI_MOLE_PER_KG_PER_MIN = "MDC_DIM_MILLI_MOLE_PER_KG_PER_MIN";
    const string MDC_DIM_MILLI_MOLE_PER_L = "MDC_DIM_MILLI_MOLE_PER_L";
    const string MDC_DIM_MILLI_MOLE_PER_M_SQ = "MDC_DIM_MILLI_MOLE_PER_M_SQ";
    const string MDC_DIM_MILLI_MOLE_PER_M_SQ_PER_DAY = "MDC_DIM_MILLI_MOLE_PER_M_SQ_PER_DAY";
    const string MDC_DIM_MILLI_MOLE_PER_M_SQ_PER_HR = "MDC_DIM_MILLI_MOLE_PER_M_SQ_PER_HR";
    const string MDC_DIM_MILLI_MOLE_PER_M_SQ_PER_MIN = "MDC_DIM_MILLI_MOLE_PER_M_SQ_PER_MIN";
    const string MDC_DIM_MILLI_MOLE_PER_MIN = "MDC_DIM_MILLI_MOLE_PER_MIN";
    const string MDC_DIM_MILLI_MOLE_PER_ML = "MDC_DIM_MILLI_MOLE_PER_ML";
    const string MDC_DIM_MILLI_OHM = "MDC_DIM_MILLI_OHM";
    const string MDC_DIM_MILLI_SEC = "MDC_DIM_MILLI_SEC";
    const string MDC_DIM_MILLI_VOLT = "MDC_DIM_MILLI_VOLT";
    const string MDC_DIM_MILLI_WATT = "MDC_DIM_MILLI_WATT";
    const string MDC_DIM_MIN = "MDC_DIM_MIN";
    const string MDC_DIM_MM_HG_PER_PERCENT = "MDC_DIM_MM_HG_PER_PERCENT";
    const string MDC_DIM_MM_HG_PER_X_L = "MDC_DIM_MM_HG_PER_X_L";
    const string MDC_DIM_MMHG = "MDC_DIM_MMHG";
    const string MDC_DIM_MMHG_MIN_PER_L = "MDC_DIM_MMHG_MIN_PER_L";
    const string MDC_DIM_MMHG_SEC_PER_ML = "MDC_DIM_MMHG_SEC_PER_ML";
    const string MDC_DIM_MON = "MDC_DIM_MON";
    const string MDC_DIM_NANO_G = "MDC_DIM_NANO_G";
    const string MDC_DIM_NANO_G_PER_DAY = "MDC_DIM_NANO_G_PER_DAY";
    const string MDC_DIM_NANO_G_PER_HR = "MDC_DIM_NANO_G_PER_HR";
    const string MDC_DIM_NANO_G_PER_KG = "MDC_DIM_NANO_G_PER_KG";
    const string MDC_DIM_NANO_G_PER_KG_PER_DAY = "MDC_DIM_NANO_G_PER_KG_PER_DAY";
    const string MDC_DIM_NANO_G_PER_KG_PER_HR = "MDC_DIM_NANO_G_PER_KG_PER_HR";
    const string MDC_DIM_NANO_G_PER_KG_PER_MIN = "MDC_DIM_NANO_G_PER_KG_PER_MIN";
    const string MDC_DIM_NANO_G_PER_LB_PER_HR = "MDC_DIM_NANO_G_PER_LB_PER_HR";
    const string MDC_DIM_NANO_G_PER_LB_PER_MIN = "MDC_DIM_NANO_G_PER_LB_PER_MIN";
    const string MDC_DIM_NANO_G_PER_M_SQ = "MDC_DIM_NANO_G_PER_M_SQ";
    const string MDC_DIM_NANO_G_PER_M_SQ_PER_DAY = "MDC_DIM_NANO_G_PER_M_SQ_PER_DAY";
    const string MDC_DIM_NANO_G_PER_M_SQ_PER_HR = "MDC_DIM_NANO_G_PER_M_SQ_PER_HR";
    const string MDC_DIM_NANO_G_PER_M_SQ_PER_MIN = "MDC_DIM_NANO_G_PER_M_SQ_PER_MIN";
    const string MDC_DIM_NANO_G_PER_MIN = "MDC_DIM_NANO_G_PER_MIN";
    const string MDC_DIM_NANO_G_PER_ML = "MDC_DIM_NANO_G_PER_ML";
    const string MDC_DIM_NANO_INTL_UNIT_PER_KG = "MDC_DIM_NANO_INTL_UNIT_PER_KG";
    const string MDC_DIM_NANO_INTL_UNIT_PER_M_SQ = "MDC_DIM_NANO_INTL_UNIT_PER_M_SQ";
    const string MDC_DIM_NANO_SEC = "MDC_DIM_NANO_SEC";
    const string MDC_DIM_NANO_VOLT = "MDC_DIM_NANO_VOLT";
    const string MDC_DIM_NANO_VOLT_SEC = "MDC_DIM_NANO_VOLT_SEC";
    const string MDC_DIM_NANO_WATT = "MDC_DIM_NANO_WATT";
    const string MDC_DIM_NOS = "MDC_DIM_NOS";
    const string MDC_DIM_O2_SAT_PERCENT_SEC = "MDC_DIM_O2_SAT_PERCENT_SEC";
    const string MDC_DIM_OHM = "MDC_DIM_OHM";
    const string MDC_DIM_OZ = "MDC_DIM_OZ";
    const string MDC_DIM_PA_PER_X_L = "MDC_DIM_PA_PER_X_L";
    const string MDC_DIM_PARTS_PER_10_TO_MINUS_12 = "MDC_DIM_PARTS_PER_10_TO_MINUS_12";
    const string MDC_DIM_PARTS_PER_10_TO_MINUS_15 = "MDC_DIM_PARTS_PER_10_TO_MINUS_15";
    const string MDC_DIM_PARTS_PER_10_TO_MINUS_3 = "MDC_DIM_PARTS_PER_10_TO_MINUS_3";
    const string MDC_DIM_PARTS_PER_10_TO_MINUS_6 = "MDC_DIM_PARTS_PER_10_TO_MINUS_6";
    const string MDC_DIM_PARTS_PER_10_TO_MINUS_9 = "MDC_DIM_PARTS_PER_10_TO_MINUS_9";
    const string MDC_DIM_PCT_PCV = "MDC_DIM_PCT_PCV";
    const string MDC_DIM_PER_CUBIC_X_M = "MDC_DIM_PER_CUBIC_X_M";
    const string MDC_DIM_PER_DAY = "MDC_DIM_PER_DAY";
    const string MDC_DIM_PER_HECTO_SEC_SQ = "MDC_DIM_PER_HECTO_SEC_SQ";
    const string MDC_DIM_PER_HR = "MDC_DIM_PER_HR";
    const string MDC_DIM_PER_KILO_OHM = "MDC_DIM_PER_KILO_OHM";
    const string MDC_DIM_PER_KILO_SEC = "MDC_DIM_PER_KILO_SEC";
    const string MDC_DIM_PER_MIN = "MDC_DIM_PER_MIN";
    const string MDC_DIM_PER_MO = "MDC_DIM_PER_MO";
    const string MDC_DIM_PER_SQ_X_M = "MDC_DIM_PER_SQ_X_M";
    const string MDC_DIM_PER_WK = "MDC_DIM_PER_WK";
    const string MDC_DIM_PER_X_G = "MDC_DIM_PER_X_G";
    const string MDC_DIM_PER_X_L = "MDC_DIM_PER_X_L";
    const string MDC_DIM_PER_X_L_PER_MIN = "MDC_DIM_PER_X_L_PER_MIN";
    const string MDC_DIM_PER_X_M = "MDC_DIM_PER_X_M";
    const string MDC_DIM_PER_X_OHM = "MDC_DIM_PER_X_OHM";
    const string MDC_DIM_PER_X_SEC = "MDC_DIM_PER_X_SEC";
    const string MDC_DIM_PER_X_SEC_SQ = "MDC_DIM_PER_X_SEC_SQ";
    const string MDC_DIM_PER_YR = "MDC_DIM_PER_YR";
    const string MDC_DIM_PERCENT = "MDC_DIM_PERCENT";
    const string MDC_DIM_PH = "MDC_DIM_PH";
    const string MDC_DIM_PSI = "MDC_DIM_PSI";
    const string MDC_DIM_PULS_PER_MIN = "MDC_DIM_PULS_PER_MIN";
    const string MDC_DIM_RBC = "MDC_DIM_RBC";
    const string MDC_DIM_RESP_PER_MIN = "MDC_DIM_RESP_PER_MIN";
    const string MDC_DIM_SEC = "MDC_DIM_SEC";
    const string MDC_DIM_SIGH = "MDC_DIM_SIGH";
    const string MDC_DIM_SQ_X_CM = "MDC_DIM_SQ_X_CM";
    const string MDC_DIM_SQ_X_INCH = "MDC_DIM_SQ_X_INCH";
    const string MDC_DIM_SQ_X_M = "MDC_DIM_SQ_X_M";
    const string MDC_DIM_SQ_X_M_PER_SEC = "MDC_DIM_SQ_X_M_PER_SEC";
    const string MDC_DIM_SQUARE_BREATHS_PER_MIN_PER_L = "MDC_DIM_SQUARE_BREATHS_PER_MIN_PER_L";
    const string MDC_DIM_TOD = "MDC_DIM_TOD";
    const string MDC_DIM_VOL_PERCENT = "MDC_DIM_VOL_PERCENT";
    const string MDC_DIM_WEEKS = "MDC_DIM_WEEKS";
    const string MDC_DIM_X_AMP_HR = "MDC_DIM_X_AMP_HR";
    const string MDC_DIM_X_AMPS = "MDC_DIM_X_AMPS";
    const string MDC_DIM_X_AMPS_PER_M = "MDC_DIM_X_AMPS_PER_M";
    const string MDC_DIM_X_BAR = "MDC_DIM_X_BAR";
    const string MDC_DIM_X_BEL = "MDC_DIM_X_BEL";
    const string MDC_DIM_X_BEL_MV = "MDC_DIM_X_BEL_MV";
    const string MDC_DIM_X_CAL = "MDC_DIM_X_CAL";
    const string MDC_DIM_X_CAL_PER_DAY = "MDC_DIM_X_CAL_PER_DAY";
    const string MDC_DIM_X_CANDELA = "MDC_DIM_X_CANDELA";
    const string MDC_DIM_X_COULOMB = "MDC_DIM_X_COULOMB";
    const string MDC_DIM_X_DROPS_PER_MIN = "MDC_DIM_X_DROPS_PER_MIN";
    const string MDC_DIM_X_DYNE = "MDC_DIM_X_DYNE";
    const string MDC_DIM_X_DYNE_SEC_PER_CM5 = "MDC_DIM_X_DYNE_SEC_PER_CM5";
    const string MDC_DIM_X_EQUIV = "MDC_DIM_X_EQUIV";
    const string MDC_DIM_X_EQUIV_PER_CM_CUBE = "MDC_DIM_X_EQUIV_PER_CM_CUBE";
    const string MDC_DIM_X_EQUIV_PER_DAY = "MDC_DIM_X_EQUIV_PER_DAY";
    const string MDC_DIM_X_EQUIV_PER_HR = "MDC_DIM_X_EQUIV_PER_HR";
    const string MDC_DIM_X_EQUIV_PER_KG = "MDC_DIM_X_EQUIV_PER_KG";
    const string MDC_DIM_X_EQUIV_PER_KG_PER_DAY = "MDC_DIM_X_EQUIV_PER_KG_PER_DAY";
    const string MDC_DIM_X_EQUIV_PER_KG_PER_HR = "MDC_DIM_X_EQUIV_PER_KG_PER_HR";
    const string MDC_DIM_X_EQUIV_PER_KG_PER_MIN = "MDC_DIM_X_EQUIV_PER_KG_PER_MIN";
    const string MDC_DIM_X_EQUIV_PER_KG_PER_SEC = "MDC_DIM_X_EQUIV_PER_KG_PER_SEC";
    const string MDC_DIM_X_EQUIV_PER_L = "MDC_DIM_X_EQUIV_PER_L";
    const string MDC_DIM_X_EQUIV_PER_LB_PER_HR = "MDC_DIM_X_EQUIV_PER_LB_PER_HR";
    const string MDC_DIM_X_EQUIV_PER_LB_PER_MIN = "MDC_DIM_X_EQUIV_PER_LB_PER_MIN";
    const string MDC_DIM_X_EQUIV_PER_M_CUBE = "MDC_DIM_X_EQUIV_PER_M_CUBE";
    const string MDC_DIM_X_EQUIV_PER_M_SQ = "MDC_DIM_X_EQUIV_PER_M_SQ";
    const string MDC_DIM_X_EQUIV_PER_M_SQ_PER_DAY = "MDC_DIM_X_EQUIV_PER_M_SQ_PER_DAY";
    const string MDC_DIM_X_EQUIV_PER_M_SQ_PER_HR = "MDC_DIM_X_EQUIV_PER_M_SQ_PER_HR";
    const string MDC_DIM_X_EQUIV_PER_M_SQ_PER_MIN = "MDC_DIM_X_EQUIV_PER_M_SQ_PER_MIN";
    const string MDC_DIM_X_EQUIV_PER_MIN = "MDC_DIM_X_EQUIV_PER_MIN";
    const string MDC_DIM_X_EQUIV_PER_ML = "MDC_DIM_X_EQUIV_PER_ML";
    const string MDC_DIM_X_EQUIV_PER_SEC = "MDC_DIM_X_EQUIV_PER_SEC";
    const string MDC_DIM_X_FARAD = "MDC_DIM_X_FARAD";
    const string MDC_DIM_X_FOOT = "MDC_DIM_X_FOOT";
    const string MDC_DIM_X_G = "MDC_DIM_X_G";
    const string MDC_DIM_X_G_FORCE_M = "MDC_DIM_X_G_FORCE_M";
    const string MDC_DIM_X_G_FORCE_M_PER_L = "MDC_DIM_X_G_FORCE_M_PER_L";
    const string MDC_DIM_X_G_FORCE_M_PER_M_SQ = "MDC_DIM_X_G_FORCE_M_PER_M_SQ";
    const string MDC_DIM_X_G_M = "MDC_DIM_X_G_M";
    const string MDC_DIM_X_G_M_PER_M_SQ = "MDC_DIM_X_G_M_PER_M_SQ";
    const string MDC_DIM_X_G_M_PER_SEC = "MDC_DIM_X_G_M_PER_SEC";
    const string MDC_DIM_X_G_M_SQ = "MDC_DIM_X_G_M_SQ";
    const string MDC_DIM_X_G_PER_CL = "MDC_DIM_X_G_PER_CL";
    const string MDC_DIM_X_G_PER_CM_CUBE = "MDC_DIM_X_G_PER_CM_CUBE";
    const string MDC_DIM_X_G_PER_DAY = "MDC_DIM_X_G_PER_DAY";
    const string MDC_DIM_X_G_PER_DL = "MDC_DIM_X_G_PER_DL";
    const string MDC_DIM_X_G_PER_G = "MDC_DIM_X_G_PER_G";
    const string MDC_DIM_X_G_PER_HR = "MDC_DIM_X_G_PER_HR";
    const string MDC_DIM_X_G_PER_KG = "MDC_DIM_X_G_PER_KG";
    const string MDC_DIM_X_G_PER_KG_PER_DAY = "MDC_DIM_X_G_PER_KG_PER_DAY";
    const string MDC_DIM_X_G_PER_KG_PER_HR = "MDC_DIM_X_G_PER_KG_PER_HR";
    const string MDC_DIM_X_G_PER_KG_PER_MIN = "MDC_DIM_X_G_PER_KG_PER_MIN";
    const string MDC_DIM_X_G_PER_KG_PER_SEC = "MDC_DIM_X_G_PER_KG_PER_SEC";
    const string MDC_DIM_X_G_PER_L = "MDC_DIM_X_G_PER_L";
    const string MDC_DIM_X_G_PER_L_PER_DAY = "MDC_DIM_X_G_PER_L_PER_DAY";
    const string MDC_DIM_X_G_PER_L_PER_HR = "MDC_DIM_X_G_PER_L_PER_HR";
    const string MDC_DIM_X_G_PER_L_PER_MIN = "MDC_DIM_X_G_PER_L_PER_MIN";
    const string MDC_DIM_X_G_PER_L_PER_SEC = "MDC_DIM_X_G_PER_L_PER_SEC";
    const string MDC_DIM_X_G_PER_LB_PER_HR = "MDC_DIM_X_G_PER_LB_PER_HR";
    const string MDC_DIM_X_G_PER_LB_PER_MIN = "MDC_DIM_X_G_PER_LB_PER_MIN";
    const string MDC_DIM_X_G_PER_M_CUBE = "MDC_DIM_X_G_PER_M_CUBE";
    const string MDC_DIM_X_G_PER_M_PER_SEC = "MDC_DIM_X_G_PER_M_PER_SEC";
    const string MDC_DIM_X_G_PER_M_SQ = "MDC_DIM_X_G_PER_M_SQ";
    const string MDC_DIM_X_G_PER_M_SQ_PER_DAY = "MDC_DIM_X_G_PER_M_SQ_PER_DAY";
    const string MDC_DIM_X_G_PER_M_SQ_PER_HR = "MDC_DIM_X_G_PER_M_SQ_PER_HR";
    const string MDC_DIM_X_G_PER_M_SQ_PER_MIN = "MDC_DIM_X_G_PER_M_SQ_PER_MIN";
    const string MDC_DIM_X_G_PER_MG = "MDC_DIM_X_G_PER_MG";
    const string MDC_DIM_X_G_PER_MIN = "MDC_DIM_X_G_PER_MIN";
    const string MDC_DIM_X_G_PER_ML = "MDC_DIM_X_G_PER_ML";
    const string MDC_DIM_X_G_PER_SEC = "MDC_DIM_X_G_PER_SEC";
    const string MDC_DIM_X_INCH = "MDC_DIM_X_INCH";
    const string MDC_DIM_X_INTL_UNIT = "MDC_DIM_X_INTL_UNIT";
    const string MDC_DIM_X_INTL_UNIT_PER_CM_CUBE = "MDC_DIM_X_INTL_UNIT_PER_CM_CUBE";
    const string MDC_DIM_X_INTL_UNIT_PER_DAY = "MDC_DIM_X_INTL_UNIT_PER_DAY";
    const string MDC_DIM_X_INTL_UNIT_PER_HR = "MDC_DIM_X_INTL_UNIT_PER_HR";
    const string MDC_DIM_X_INTL_UNIT_PER_KG = "MDC_DIM_X_INTL_UNIT_PER_KG";
    const string MDC_DIM_X_INTL_UNIT_PER_KG_PER_DAY = "MDC_DIM_X_INTL_UNIT_PER_KG_PER_DAY";
    const string MDC_DIM_X_INTL_UNIT_PER_KG_PER_HR = "MDC_DIM_X_INTL_UNIT_PER_KG_PER_HR";
    const string MDC_DIM_X_INTL_UNIT_PER_KG_PER_MIN = "MDC_DIM_X_INTL_UNIT_PER_KG_PER_MIN";
    const string MDC_DIM_X_INTL_UNIT_PER_KG_PER_SEC = "MDC_DIM_X_INTL_UNIT_PER_KG_PER_SEC";
    const string MDC_DIM_X_INTL_UNIT_PER_L = "MDC_DIM_X_INTL_UNIT_PER_L";
    const string MDC_DIM_X_INTL_UNIT_PER_LB_PER_HR = "MDC_DIM_X_INTL_UNIT_PER_LB_PER_HR";
    const string MDC_DIM_X_INTL_UNIT_PER_LB_PER_MIN = "MDC_DIM_X_INTL_UNIT_PER_LB_PER_MIN";
    const string MDC_DIM_X_INTL_UNIT_PER_M_CUBE = "MDC_DIM_X_INTL_UNIT_PER_M_CUBE";
    const string MDC_DIM_X_INTL_UNIT_PER_M_SQ = "MDC_DIM_X_INTL_UNIT_PER_M_SQ";
    const string MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_DAY = "MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_DAY";
    const string MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_HR = "MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_HR";
    const string MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_MIN = "MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_MIN";
    const string MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_SEC = "MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_SEC";
    const string MDC_DIM_X_INTL_UNIT_PER_MIN = "MDC_DIM_X_INTL_UNIT_PER_MIN";
    const string MDC_DIM_X_INTL_UNIT_PER_ML = "MDC_DIM_X_INTL_UNIT_PER_ML";
    const string MDC_DIM_X_INTL_UNIT_PER_SEC = "MDC_DIM_X_INTL_UNIT_PER_SEC";
    const string MDC_DIM_X_JOULES = "MDC_DIM_X_JOULES";
    const string MDC_DIM_X_JOULES_PER_BREATH = "MDC_DIM_X_JOULES_PER_BREATH";
    const string MDC_DIM_X_JOULES_PER_L = "MDC_DIM_X_JOULES_PER_L";
    const string MDC_DIM_X_L = "MDC_DIM_X_L";
    const string MDC_DIM_X_L_PER_BEAT = "MDC_DIM_X_L_PER_BEAT";
    const string MDC_DIM_X_L_PER_BREATH = "MDC_DIM_X_L_PER_BREATH";
    const string MDC_DIM_X_L_PER_CM_H2O = "MDC_DIM_X_L_PER_CM_H2O";
    const string MDC_DIM_X_L_PER_CM_H2O_PER_KG = "MDC_DIM_X_L_PER_CM_H2O_PER_KG";
    const string MDC_DIM_X_L_PER_DAY = "MDC_DIM_X_L_PER_DAY";
    const string MDC_DIM_X_L_PER_DL = "MDC_DIM_X_L_PER_DL";
    const string MDC_DIM_X_L_PER_HR = "MDC_DIM_X_L_PER_HR";
    const string MDC_DIM_X_L_PER_KG = "MDC_DIM_X_L_PER_KG";
    const string MDC_DIM_X_L_PER_KG_PER_DAY = "MDC_DIM_X_L_PER_KG_PER_DAY";
    const string MDC_DIM_X_L_PER_KG_PER_HR = "MDC_DIM_X_L_PER_KG_PER_HR";
    const string MDC_DIM_X_L_PER_L = "MDC_DIM_X_L_PER_L";
    const string MDC_DIM_X_L_PER_M_SQ = "MDC_DIM_X_L_PER_M_SQ";
    const string MDC_DIM_X_L_PER_M_SQ_PER_DAY = "MDC_DIM_X_L_PER_M_SQ_PER_DAY";
    const string MDC_DIM_X_L_PER_M_SQ_PER_HR = "MDC_DIM_X_L_PER_M_SQ_PER_HR";
    const string MDC_DIM_X_L_PER_M_SQ_PER_MIN = "MDC_DIM_X_L_PER_M_SQ_PER_MIN";
    const string MDC_DIM_X_L_PER_MIN = "MDC_DIM_X_L_PER_MIN";
    const string MDC_DIM_X_L_PER_MIN_PER_KG = "MDC_DIM_X_L_PER_MIN_PER_KG";
    const string MDC_DIM_X_L_PER_MIN_PER_M_SQ = "MDC_DIM_X_L_PER_MIN_PER_M_SQ";
    const string MDC_DIM_X_L_PER_MIN_PER_ML_HG = "MDC_DIM_X_L_PER_MIN_PER_ML_HG";
    const string MDC_DIM_X_L_PER_MM_HG = "MDC_DIM_X_L_PER_MM_HG";
    const string MDC_DIM_X_L_PER_MM_PA = "MDC_DIM_X_L_PER_MM_PA";
    const string MDC_DIM_X_L_PER_SEC = "MDC_DIM_X_L_PER_SEC";
    const string MDC_DIM_X_L_SQ_PER_SEC = "MDC_DIM_X_L_SQ_PER_SEC";
    const string MDC_DIM_X_LB = "MDC_DIM_X_LB";
    const string MDC_DIM_X_LUMEN_PER_M_SQ = "MDC_DIM_X_LUMEN_PER_M_SQ";
    const string MDC_DIM_X_M = "MDC_DIM_X_M";
    const string MDC_DIM_X_M_PER_MIN = "MDC_DIM_X_M_PER_MIN";
    const string MDC_DIM_X_M_PER_PASCAL_SEC = "MDC_DIM_X_M_PER_PASCAL_SEC";
    const string MDC_DIM_X_M_PER_SEC = "MDC_DIM_X_M_PER_SEC";
    const string MDC_DIM_X_M_PER_VOLT = "MDC_DIM_X_M_PER_VOLT";
    const string MDC_DIM_X_MOLE = "MDC_DIM_X_MOLE";
    const string MDC_DIM_X_MOLE_PER_CM_CUBE = "MDC_DIM_X_MOLE_PER_CM_CUBE";
    const string MDC_DIM_X_MOLE_PER_DAY = "MDC_DIM_X_MOLE_PER_DAY";
    const string MDC_DIM_X_MOLE_PER_HR = "MDC_DIM_X_MOLE_PER_HR";
    const string MDC_DIM_X_MOLE_PER_KG = "MDC_DIM_X_MOLE_PER_KG";
    const string MDC_DIM_X_MOLE_PER_KG_PER_DAY = "MDC_DIM_X_MOLE_PER_KG_PER_DAY";
    const string MDC_DIM_X_MOLE_PER_KG_PER_HR = "MDC_DIM_X_MOLE_PER_KG_PER_HR";
    const string MDC_DIM_X_MOLE_PER_KG_PER_MIN = "MDC_DIM_X_MOLE_PER_KG_PER_MIN";
    const string MDC_DIM_X_MOLE_PER_KG_PER_SEC = "MDC_DIM_X_MOLE_PER_KG_PER_SEC";
    const string MDC_DIM_X_MOLE_PER_L = "MDC_DIM_X_MOLE_PER_L";
    const string MDC_DIM_X_MOLE_PER_M_CUBE = "MDC_DIM_X_MOLE_PER_M_CUBE";
    const string MDC_DIM_X_MOLE_PER_M_SQ = "MDC_DIM_X_MOLE_PER_M_SQ";
    const string MDC_DIM_X_MOLE_PER_M_SQ_PER_DAY = "MDC_DIM_X_MOLE_PER_M_SQ_PER_DAY";
    const string MDC_DIM_X_MOLE_PER_M_SQ_PER_HR = "MDC_DIM_X_MOLE_PER_M_SQ_PER_HR";
    const string MDC_DIM_X_MOLE_PER_M_SQ_PER_MIN = "MDC_DIM_X_MOLE_PER_M_SQ_PER_MIN";
    const string MDC_DIM_X_MOLE_PER_M_SQ_PER_SEC = "MDC_DIM_X_MOLE_PER_M_SQ_PER_SEC";
    const string MDC_DIM_X_MOLE_PER_MIN = "MDC_DIM_X_MOLE_PER_MIN";
    const string MDC_DIM_X_MOLE_PER_ML = "MDC_DIM_X_MOLE_PER_ML";
    const string MDC_DIM_X_MOLE_PER_MOLE = "MDC_DIM_X_MOLE_PER_MOLE";
    const string MDC_DIM_X_MOLE_PER_SEC = "MDC_DIM_X_MOLE_PER_SEC";
    const string MDC_DIM_X_NEWTON = "MDC_DIM_X_NEWTON";
    const string MDC_DIM_X_NEWTON_SEC = "MDC_DIM_X_NEWTON_SEC";
    const string MDC_DIM_X_NUTR_CAL = "MDC_DIM_X_NUTR_CAL";
    const string MDC_DIM_X_OHM = "MDC_DIM_X_OHM";
    const string MDC_DIM_X_OHM_M = "MDC_DIM_X_OHM_M";
    const string MDC_DIM_X_OSM = "MDC_DIM_X_OSM";
    const string MDC_DIM_X_OSM_PER_KG = "MDC_DIM_X_OSM_PER_KG";
    const string MDC_DIM_X_OSM_PER_L = "MDC_DIM_X_OSM_PER_L";
    const string MDC_DIM_X_OZ = "MDC_DIM_X_OZ";
    const string MDC_DIM_X_PA_PER_PERCENT = "MDC_DIM_X_PA_PER_PERCENT";
    const string MDC_DIM_X_PASCAL = "MDC_DIM_X_PASCAL";
    const string MDC_DIM_X_PASCAL_SEC_PER_L = "MDC_DIM_X_PASCAL_SEC_PER_L";
    const string MDC_DIM_X_PASCAL_SEC_PER_M_CUBE = "MDC_DIM_X_PASCAL_SEC_PER_M_CUBE";
    const string MDC_DIM_X_RAD_PER_SEC = "MDC_DIM_X_RAD_PER_SEC";
    const string MDC_DIM_X_ROTATIONS_PER_MIN = "MDC_DIM_X_ROTATIONS_PER_MIN";
    const string MDC_DIM_X_SEC = "MDC_DIM_X_SEC";
    const string MDC_DIM_X_TESLA = "MDC_DIM_X_TESLA";
    const string MDC_DIM_X_VOLT = "MDC_DIM_X_VOLT";
    const string MDC_DIM_X_VOLT_PER_SEC = "MDC_DIM_X_VOLT_PER_SEC";
    const string MDC_DIM_X_VOLT_SEC = "MDC_DIM_X_VOLT_SEC";
    const string MDC_DIM_X_WATT = "MDC_DIM_X_WATT";
    const string MDC_DIM_X_YARD = "MDC_DIM_X_YARD";
    const string MDC_DIM_YR = "MDC_DIM_YR";
    const string MDCX_DIM_MILLI_MOLE_PER_M_SQ_PER_SEC = "MDCX_DIM_MILLI_MOLE_PER_M_SQ_PER_SEC";
    const string MDCX_DIM_X_L_PER_KG_PER_MIN = "MDCX_DIM_X_L_PER_KG_PER_MIN";
    const string UOM_MDC = "UOM_MDC";


};

#endif
