package org.mdpnp.devices.philips.intellivue;

import org.mdpnp.devices.philips.intellivue.data.UnitCode;

public class RosettaUnits {
    public static final String units(UnitCode unit) {
        if(null == unit) {
            return rosetta.MDC_DIM_DIMLESS.VALUE;
        }
        switch(unit) {
        case NOM_DIM_NOS:
            return rosetta.MDC_DIM_NOS.VALUE;
        case NOM_DIM_DIMLESS:
            return rosetta.MDC_DIM_DIMLESS.VALUE;
        case NOM_DIM_PERCENT:
            return rosetta.MDC_DIM_PERCENT.VALUE;
        case NOM_DIM_X_MOLE_PER_MOLE:
            return rosetta.MDC_DIM_X_MOLE_PER_MOLE.VALUE;
        case NOM_DIM_PH:
            return rosetta.MDC_DIM_PH.VALUE;
        case NOM_DIM_DROP:
            return rosetta.MDC_DIM_DROP.VALUE;
        case NOM_DIM_RBC:
            return rosetta.MDC_DIM_RBC.VALUE;
        case NOM_DIM_BEAT:
            return rosetta.MDC_DIM_BEAT.VALUE;
        case NOM_DIM_BREATH:
            return rosetta.MDC_DIM_BREATH.VALUE;
        case NOM_DIM_CELL:
            return rosetta.MDC_DIM_CELL.VALUE;
        case NOM_DIM_COUGH:
            return rosetta.MDC_DIM_COUGH.VALUE;
        case NOM_DIM_SIGH:
            return rosetta.MDC_DIM_SIGH.VALUE;
        case NOM_DIM_PCT_PCV:
            return rosetta.MDC_DIM_PCT_PCV.VALUE;
        case NOM_DIM_X_M:
            return rosetta.MDC_DIM_X_M.VALUE;
        case NOM_DIM_CENTI_M:
            return rosetta.MDC_DIM_CENTI_M.VALUE;
        case NOM_DIM_MILLI_M:
            return rosetta.MDC_DIM_MILLI_M.VALUE;
        case NOM_DIM_MICRO_M:
            return rosetta.MDC_DIM_MICRO_M.VALUE;
        case NOM_DIM_X_INCH:
            return rosetta.MDC_DIM_X_INCH.VALUE;
        case NOM_DIM_MILLI_L_PER_M_SQ:
            return rosetta.MDC_DIM_MILLI_L_PER_M_SQ.VALUE;
        case NOM_DIM_PER_X_M:
            return rosetta.MDC_DIM_PER_X_M.VALUE;
        case NOM_DIM_SQ_X_M:
            return rosetta.MDC_DIM_SQ_X_M.VALUE;
        case NOM_DIM_SQ_X_INCH:
            return rosetta.MDC_DIM_SQ_X_INCH.VALUE;
        case NOM_DIM_CUBIC_X_M:
            return rosetta.MDC_DIM_CUBIC_X_M.VALUE;
        case NOM_DIM_X_L:
            return rosetta.MDC_DIM_X_L.VALUE;
        case NOM_DIM_MILLI_L:
            return rosetta.MDC_DIM_MILLI_L.VALUE;
        case NOM_DIM_MILLI_L_PER_BREATH:
            return rosetta.MDC_DIM_MILLI_L_PER_BREATH.VALUE;
        case NOM_DIM_PER_X_L:
            return rosetta.MDC_DIM_PER_X_L.VALUE;
        case NOM_DIM_X_G:
            return rosetta.MDC_DIM_X_G.VALUE;
        case NOM_DIM_KILO_G:
            return rosetta.MDC_DIM_KILO_G.VALUE;
        case NOM_DIM_MILLI_G:
            return rosetta.MDC_DIM_MILLI_G.VALUE;
        case NOM_DIM_MICRO_G:
            return rosetta.MDC_DIM_MICRO_G.VALUE;
        case NOM_DIM_NANO_G:
            return rosetta.MDC_DIM_NANO_G.VALUE;
        case NOM_DIM_X_LB:
            return rosetta.MDC_DIM_X_LB.VALUE;
        case NOM_DIM_X_OZ:
            return rosetta.MDC_DIM_X_OZ.VALUE;
        case NOM_DIM_PER_X_G:
            return rosetta.MDC_DIM_PER_X_G.VALUE;
        case NOM_DIM_X_G_M:
            return rosetta.MDC_DIM_X_G_M.VALUE;
        case NOM_DIM_X_G_M_PER_M_SQ:
            return rosetta.MDC_DIM_X_G_M_PER_M_SQ.VALUE;
        case NOM_DIM_KG_PER_M_SQ:
            return rosetta.MDC_DIM_KG_PER_M_SQ.VALUE;
        case NOM_DIM_X_G_PER_CM_CUBE:
            return rosetta.MDC_DIM_X_G_PER_CM_CUBE.VALUE;
        case NOM_DIM_X_G_PER_L:
            return rosetta.MDC_DIM_X_G_PER_L.VALUE;
        case NOM_DIM_X_G_PER_DL:
            return rosetta.MDC_DIM_X_G_PER_DL.VALUE;
        case NOM_DIM_MILLI_G_PER_DL:
            return rosetta.MDC_DIM_MILLI_G_PER_DL.VALUE;
        case NOM_DIM_X_G_PER_ML:
            return rosetta.MDC_DIM_X_G_PER_ML.VALUE;
        case NOM_DIM_MILLI_G_PER_ML:
            return rosetta.MDC_DIM_MILLI_G_PER_ML.VALUE;
        case NOM_DIM_MICRO_G_PER_ML:
            return rosetta.MDC_DIM_MICRO_G_PER_ML.VALUE;
        case NOM_DIM_NANO_G_PER_ML:
            return rosetta.MDC_DIM_NANO_G_PER_ML.VALUE;
        case NOM_DIM_SEC:
            return rosetta.MDC_DIM_SEC.VALUE;
        case NOM_DIM_MILLI_SEC:
            return rosetta.MDC_DIM_MILLI_SEC.VALUE;
        case NOM_DIM_MICRO_SEC:
            return rosetta.MDC_DIM_MICRO_SEC.VALUE;
        case NOM_DIM_MIN:
            return rosetta.MDC_DIM_MIN.VALUE;
        case NOM_DIM_HR:
            return rosetta.MDC_DIM_HR.VALUE;
        case NOM_DIM_DAY:
            return rosetta.MDC_DIM_DAY.VALUE;
        case NOM_DIM_WEEKS:
            return rosetta.MDC_DIM_WEEKS.VALUE;
        case NOM_DIM_MON:
            return rosetta.MDC_DIM_MON.VALUE;
        case NOM_DIM_YR:
            return rosetta.MDC_DIM_YR.VALUE;
        case NOM_DIM_TOD:
            return rosetta.MDC_DIM_TOD.VALUE;
        case NOM_DIM_DATE:
            return rosetta.MDC_DIM_DATE.VALUE;
        case NOM_DIM_PER_X_SEC:
            return rosetta.MDC_DIM_PER_X_SEC.VALUE;
        case NOM_DIM_HZ:
            return rosetta.MDC_DIM_HZ.VALUE;
        case NOM_DIM_PER_MIN:
            return rosetta.MDC_DIM_PER_MIN.VALUE;
        case NOM_DIM_PER_HR:
            return rosetta.MDC_DIM_PER_HR.VALUE;
        case NOM_DIM_PER_DAY:
            return rosetta.MDC_DIM_PER_DAY.VALUE;
        case NOM_DIM_PER_WK:
            return rosetta.MDC_DIM_PER_WK.VALUE;
        case NOM_DIM_PER_MO:
            return rosetta.MDC_DIM_PER_MO.VALUE;
        case NOM_DIM_PER_YR:
            return rosetta.MDC_DIM_PER_YR.VALUE;
        case NOM_DIM_BEAT_PER_MIN:
            return rosetta.MDC_DIM_BEAT_PER_MIN.VALUE;
        case NOM_DIM_PULS_PER_MIN:
            return rosetta.MDC_DIM_PULS_PER_MIN.VALUE;
        case NOM_DIM_RESP_PER_MIN:
            return rosetta.MDC_DIM_RESP_PER_MIN.VALUE;
        case NOM_DIM_X_M_PER_SEC:
            return rosetta.MDC_DIM_X_M_PER_SEC.VALUE;
        case NOM_DIM_MILLI_M_PER_SEC:
            return rosetta.MDC_DIM_MILLI_M_PER_SEC.VALUE;
        case NOM_DIM_X_L_PER_MIN_PER_M_SQ:
            return rosetta.MDC_DIM_X_L_PER_MIN_PER_M_SQ.VALUE;
        case NOM_DIM_MILLI_L_PER_MIN_PER_M_SQ:
            return rosetta.MDC_DIM_MILLI_L_PER_MIN_PER_M_SQ.VALUE;
        case NOM_DIM_SQ_X_M_PER_SEC:
            return rosetta.MDC_DIM_SQ_X_M_PER_SEC.VALUE;
        case NOM_DIM_CUBIC_X_M_PER_SEC:
            return rosetta.MDC_DIM_CUBIC_X_M_PER_SEC.VALUE;
        case NOM_DIM_X_L_PER_SEC:
            return rosetta.MDC_DIM_X_L_PER_SEC.VALUE;
        case NOM_DIM_X_L_PER_MIN:
            return rosetta.MDC_DIM_X_L_PER_MIN.VALUE;
        case NOM_DIM_MILLI_L_PER_MIN:
            return rosetta.MDC_DIM_MILLI_L_PER_MIN.VALUE;
        case NOM_DIM_X_L_PER_HR:
            return rosetta.MDC_DIM_X_L_PER_HR.VALUE;
        case NOM_DIM_MILLI_L_PER_HR:
            return rosetta.MDC_DIM_MILLI_L_PER_HR.VALUE;
        case NOM_DIM_X_L_PER_DAY:
            return rosetta.MDC_DIM_X_L_PER_DAY.VALUE;
        case NOM_DIM_MILLI_L_PER_KG:
            return rosetta.MDC_DIM_MILLI_L_PER_KG.VALUE;
        case NOM_DIM_X_G_PER_MIN:
            return rosetta.MDC_DIM_X_G_PER_MIN.VALUE;
        case NOM_DIM_MILLI_G_PER_MIN:
            return rosetta.MDC_DIM_MILLI_G_PER_MIN.VALUE;
        case NOM_DIM_MICRO_G_PER_MIN:
            return rosetta.MDC_DIM_MICRO_G_PER_MIN.VALUE;
        case NOM_DIM_NANO_G_PER_MIN:
            return rosetta.MDC_DIM_NANO_G_PER_MIN.VALUE;
        case NOM_DIM_X_G_PER_HR:
            return rosetta.MDC_DIM_X_G_PER_HR.VALUE;
        case NOM_DIM_MILLI_G_PER_HR:
            return rosetta.MDC_DIM_MILLI_G_PER_HR.VALUE;
        case NOM_DIM_MICRO_G_PER_HR:
            return rosetta.MDC_DIM_MICRO_G_PER_HR.VALUE;
        case NOM_DIM_NANO_G_PER_HR:
            return rosetta.MDC_DIM_NANO_G_PER_HR.VALUE;
        case NOM_DIM_X_G_PER_KG_PER_MIN:
            return rosetta.MDC_DIM_X_G_PER_KG_PER_MIN.VALUE;
        case NOM_DIM_MILLI_G_PER_KG_PER_MIN:
            return rosetta.MDC_DIM_MILLI_G_PER_KG_PER_MIN.VALUE;
        case NOM_DIM_MICRO_G_PER_KG_PER_MIN:
            return rosetta.MDC_DIM_MICRO_G_PER_KG_PER_MIN.VALUE;
        case NOM_DIM_NANO_G_PER_KG_PER_MIN:
            return rosetta.MDC_DIM_NANO_G_PER_KG_PER_MIN.VALUE;
        case NOM_DIM_X_G_PER_KG_PER_HR:
            return rosetta.MDC_DIM_X_G_PER_KG_PER_HR.VALUE;
        case NOM_DIM_MILLI_G_PER_KG_PER_HR:
            return rosetta.MDC_DIM_MILLI_G_PER_KG_PER_HR.VALUE;
        case NOM_DIM_MICRO_G_PER_KG_PER_HR:
            return rosetta.MDC_DIM_MICRO_G_PER_KG_PER_HR.VALUE;
        case NOM_DIM_NANO_G_PER_KG_PER_HR:
            return rosetta.MDC_DIM_NANO_G_PER_KG_PER_HR.VALUE;
        case NOM_DIM_X_NEWTON_SEC:
            return rosetta.MDC_DIM_X_NEWTON_SEC.VALUE;
        case NOM_DIM_X_NEWTON:
            return rosetta.MDC_DIM_X_NEWTON.VALUE;
        case NOM_DIM_X_PASCAL:
            return rosetta.MDC_DIM_X_PASCAL.VALUE;
        case NOM_DIM_HECTO_PASCAL:
            return rosetta.MDC_DIM_HECTO_PASCAL.VALUE;
        case NOM_DIM_KILO_PASCAL:
            return rosetta.MDC_DIM_KILO_PASCAL.VALUE;
        case NOM_DIM_MMHG:
            return rosetta.MDC_DIM_MMHG.VALUE;
        case NOM_DIM_CM_H2O:
            return rosetta.MDC_DIM_CM_H2O.VALUE;
        case NOM_DIM_X_JOULES:
            return rosetta.MDC_DIM_X_JOULES.VALUE;
        case NOM_DIM_EVOLT:
            return rosetta.MDC_DIM_EVOLT.VALUE;
        case NOM_DIM_X_WATT:
            return rosetta.MDC_DIM_X_WATT.VALUE;
        case NOM_DIM_MILLI_WATT:
            return rosetta.MDC_DIM_MILLI_WATT.VALUE;
        case NOM_DIM_NANO_WATT:
            return rosetta.MDC_DIM_NANO_WATT.VALUE;
        case NOM_DIM_X_AMPS:
            return rosetta.MDC_DIM_X_AMPS.VALUE;
        case NOM_DIM_X_COULOMB:
            return rosetta.MDC_DIM_X_COULOMB.VALUE;
        case NOM_DIM_X_VOLT:
            return rosetta.MDC_DIM_X_VOLT.VALUE;
        case NOM_DIM_MILLI_VOLT:
            return rosetta.MDC_DIM_MILLI_VOLT.VALUE;
        case NOM_DIM_MICRO_VOLT:
            return rosetta.MDC_DIM_MICRO_VOLT.VALUE;
        case NOM_DIM_X_OHM:
            return rosetta.MDC_DIM_X_OHM.VALUE;
        case NOM_DIM_X_FARAD:
            return rosetta.MDC_DIM_X_FARAD.VALUE;
        case NOM_DIM_KELVIN:
            return rosetta.MDC_DIM_KELVIN.VALUE;
        case NOM_DIM_FAHR:
            return rosetta.MDC_DIM_FAHR.VALUE;
        case NOM_DIM_X_CANDELA:
            return rosetta.MDC_DIM_X_CANDELA.VALUE;
        case NOM_DIM_X_MOLE:
            return rosetta.MDC_DIM_X_MOLE.VALUE;
        case NOM_DIM_MILLI_MOLE:
            return rosetta.MDC_DIM_MILLI_MOLE.VALUE;
        case NOM_DIM_MILLI_EQUIV:
            return rosetta.MDC_DIM_MILLI_EQUIV.VALUE;
        case NOM_DIM_MILLI_MOLE_PER_L:
            return rosetta.MDC_DIM_MILLI_MOLE_PER_L.VALUE;
        case NOM_DIM_MILLI_EQUIV_PER_L:
            return rosetta.MDC_DIM_MILLI_EQUIV_PER_L.VALUE;
        case NOM_DIM_MILLI_EQUIV_PER_DAY:
            return rosetta.MDC_DIM_MILLI_EQUIV_PER_DAY.VALUE;
        case NOM_DIM_X_INTL_UNIT:
            return rosetta.MDC_DIM_X_INTL_UNIT.VALUE;
        case NOM_DIM_MILLI_INTL_UNIT:
            return rosetta.MDC_DIM_MILLI_INTL_UNIT.VALUE;
        case NOM_DIM_X_INTL_UNIT_PER_CM_CUBE:
            return rosetta.MDC_DIM_X_INTL_UNIT_PER_CM_CUBE.VALUE;
        case NOM_DIM_X_INTL_UNIT_PER_L:
            return rosetta.MDC_DIM_X_INTL_UNIT_PER_L.VALUE;
        case NOM_DIM_X_INTL_UNIT_PER_ML:
            return rosetta.MDC_DIM_X_INTL_UNIT_PER_ML.VALUE;
        case NOM_DIM_MILLI_INTL_UNIT_PER_ML:
            return rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_ML.VALUE;
        case NOM_DIM_X_INTL_UNIT_PER_MIN:
            return rosetta.MDC_DIM_X_INTL_UNIT_PER_MIN.VALUE;
        case NOM_DIM_MILLI_INTL_UNIT_PER_MIN:
            return rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_MIN.VALUE;
        case NOM_DIM_X_INTL_UNIT_PER_HR:
            return rosetta.MDC_DIM_X_INTL_UNIT_PER_HR.VALUE;
        case NOM_DIM_MILLI_INTL_UNIT_PER_HR:
            return rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_HR.VALUE;
        case NOM_DIM_X_INTL_UNIT_PER_KG_PER_MIN:
            return rosetta.MDC_DIM_X_INTL_UNIT_PER_KG_PER_MIN.VALUE;
        case NOM_DIM_MILLI_INTL_UNIT_PER_KG_PER_MIN:
            return rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_MIN.VALUE;
        case NOM_DIM_X_INTL_UNIT_PER_KG_PER_HR:
            return rosetta.MDC_DIM_X_INTL_UNIT_PER_KG_PER_HR.VALUE;
        case NOM_DIM_MILLI_INTL_UNIT_PER_KG_PER_HR:
            return rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_HR.VALUE;
        case NOM_DIM_MILLI_L_PER_CM_H2O:
            return rosetta.MDC_DIM_MILLI_L_PER_CM_H2O.VALUE;
        case NOM_DIM_CM_H2O_PER_L_PER_SEC:
            return rosetta.MDC_DIM_CM_H2O_PER_L_PER_SEC.VALUE;
        case NOM_DIM_CM_H2O_PER_PERCENT:
            return rosetta.MDC_DIM_CM_H2O_PER_PERCENT.VALUE;
        case NOM_DIM_DYNE_SEC_PER_M_SQ_PER_CM_5:
            return rosetta.MDC_DIM_DYNE_SEC_PER_M_SQ_PER_CM_5.VALUE;
        case NOM_DIM_DEGC:
            return rosetta.MDC_DIM_DEGC.VALUE;
        case NOM_DIM_CM_H2O_PER_L:
            return rosetta.MDC_DIM_CM_H2O_PER_L.VALUE;
        case NOM_DIM_MM_HG_PER_PERCENT:
            return rosetta.MDC_DIM_MM_HG_PER_PERCENT.VALUE;
        case NOM_DIM_X_L_PER_MM_HG:
            return rosetta.MDC_DIM_X_L_PER_MM_HG.VALUE;
        case NOM_DIM_MILLI_L_PER_DL:
            return rosetta.MDC_DIM_MILLI_L_PER_DL.VALUE;
        case NOM_DIM_DECIBEL:
            return rosetta.MDC_DIM_DECIBEL.VALUE;
        case NOM_DIM_BEAT_PER_MIN_PER_X_L:
            return rosetta.MDC_DIM_BEAT_PER_MIN_PER_X_L.VALUE;
        case NOM_DIM_PER_X_L_PER_MIN:
            return rosetta.MDC_DIM_PER_X_L_PER_MIN.VALUE;
        case NOM_DIM_X_M_PER_MIN:
            return rosetta.MDC_DIM_X_M_PER_MIN.VALUE;
        case NOM_DIM_X_L_PER_KG_PER_HR:
            return rosetta.MDC_DIM_X_L_PER_KG_PER_HR.VALUE;
        case NOM_DIM_MILLI_L_PER_KG_PER_HR:
            return rosetta.MDC_DIM_MILLI_L_PER_KG_PER_HR.VALUE;
        case NOM_DIM_X_L_PER_MIN_PER_KG:
            return rosetta.MDC_DIM_X_L_PER_MIN_PER_KG.VALUE;
        case NOM_DIM_MILLI_L_PER_MIN_PER_KG:
            return rosetta.MDC_DIM_MILLI_L_PER_MIN_PER_KG.VALUE;
        case NOM_DIM_DIV:
        case NOM_DIM_PARTS_PER_THOUSAND:
        case NOM_DIM_PARTS_PER_MILLION:
        case NOM_DIM_PARTS_PER_BILLION:
        case NOM_DIM_PARTS_PER_TRILLION:
        case NOM_DIM_PER_MILLI_M:
        case NOM_DIM_CUBIC_CENTI_M:
        case NOM_DIM_CUBIC_MILLI_M:
        case NOM_DIM_PER_CUBIC_CENTI_M:
        case NOM_DIM_PER_CUBIC_MILLI_M:
        case NOM_DIM_PER_MICRO_L:
        case NOM_DIM_PER_NANO_LITER:
        case NOM_DIM_KILO_G_M:
        case NOM_DIM_KILO_G_M_PER_M_SQ:
        case NOM_DIM_KILO_G_M_SQ:
        case NOM_DIM_KILO_G_PER_M_CUBE:
        case NOM_DIM_MILLI_G_PER_CM_CUBE:
        case NOM_DIM_MICRO_G_PER_CM_CUBE:
        case NOM_DIM_NANO_G_PER_CM_CUBE:
        case NOM_DIM_MILLI_G_PER_L:
        case NOM_DIM_MICRO_G_PER_L:
        case NOM_DIM_NANO_G_PER_L:
        case NOM_DIM_MICRO_G_PER_DL:
        case NOM_DIM_PICO_G_PER_ML:
        case NOM_DIM_SQ_CENTI_M_PER_SEC:
        case NOM_DIM_CUBIC_CENTI_M_PER_SEC:
        case NOM_DIM_DECI_L_PER_MIN:
        case NOM_DIM_MILLI_L_PER_DAY:
        case NOM_DIM_KILO_G_PER_SEC:
        case NOM_DIM_KILO_G_PER_MIN:
        case NOM_DIM_KILO_G_PER_HR:  
        case NOM_DIM_KILO_G_PER_DAY:
        case NOM_DIM_KILO_G_PER_L_SEC:
        case NOM_DIM_KILO_G_PER_M_PER_SEC:
        case NOM_DIM_KILO_G_M_PER_SEC:
        case NOM_DIM_MILLI_BAR:
        case NOM_DIM_PICO_WATT:
        case NOM_DIM_X_DYNE_PER_SEC_PER_CM5:
        case NOM_DIM_MILLI_AMPS:
        case NOM_DIM_MICRO_COULOMB:
        case NOM_DIM_OHM_K:
        case NOM_DIM_MILLI_OSM:
        case NOM_DIM_MILLI_OSM_PER_L:
        case NOM_DIM_MICRO_MOLE_PER_L:
        case NOM_DIM_MILLI_MOL_PER_KG:
        case NOM_DIM_MILLI_INTL_UNIT_PER_CM_CUBE:
        case NOM_DIM_MEGA_INTL_UNIT_PER_L:
        case NOM_DIM_MILLI_L_SQ_PER_SEC:
        case NOM_DIM_MILLI_AMP_HR:
        case NOM_DIM_KILO_PA_PER_PERCENT:
        case NOM_DIM_X_G_PER_MILLI_G:
        case NOM_DIM_MILLI_G_PER_MILLI_G:
        case NOM_DIM_MILLI_L_PER_MM_HG:
        case NOM_DIM_BEAT_PER_MIN_PER_MILLI_L:
        case NOM_DIM_CENTI_M_PER_MIN:
        case NOM_DIM_COMPLEX:
        case NOM_DIM_COUNT:
        case NOM_DIM_PART:
        case NOM_DIM_PULS:
        case NOM_DIM_UV_PP:
        case NOM_DIM_UV_SQ:
        case NOM_DIM_LUMEN:
        case NOM_DIM_LB_PER_INCH_SQ:
        case NOM_DIM_MM_HG_PER_SEC:
        case NOM_DIM_ML_PER_SEC:
        case NOM_DIM_BEAT_PER_MIN_PER_ML_C:
        case NOM_DIM_X_JOULE_PER_DAY:
        case NOM_DIM_KILO_JOULE_PER_DAY:
        case NOM_DIM_MEGA_JOULE_PER_DAY:
        case NOM_DIM_X_CALORIE:
        case NOM_DIM_KILO_CALORIE:
        case NOM_DIM_MEGA_CALORIE:
        case NOM_DIM_X_CALORIE_PER_DAY:
        case NOM_DIM_KILO_CALORIE_PER_DAY:
        case NOM_DIM_MEGA_CALORIE_PER_DAY:
        case NOM_DIM_X_CALORIE_PER_ML:
        case NOM_DIM_KILO_CALORIE_PER_ML:
        case NOM_DIM_X_JOULE_PER_ML:
        case NOM_DIM_KILO_JOULE_PER_ML:
        case NOM_DIM_X_REV_PER_MIN:
        case NOM_DIM_PER_L_PER_MIN_PER_KG:
        case NOM_DIM_X_L_PER_MILLI_BAR:
        case NOM_DIM_MILLI_L_PER_MILLI_BAR:
        case NOM_DIM_X_BAR_PER_LITER_PER_SEC:
        case NOM_DIM_MILLI_BAR_PER_LITER_PER_SEC:
        case NOM_DIM_X_BAR_PER_LITER:
        case NOM_DIM_MILLI_BAR_PER_LITER:
        case NOM_DIM_VOLT_PER_MILLI_VOLT:
        case NOM_DIM_CM_H2O_PER_MICRO_VOLT:
        case NOM_DIM_X_JOULE_PER_LITER:
        case NOM_DIM_X_L_PER_BAR:
        case NOM_DIM_X_M_PER_MILLI_VOLT:
        case NOM_DIM_MILLI_M_PER_MILLI_VOLT:
        case NOM_DIM_X_PASCAL_PER_L_PER_SEC:
        case NOM_DIM_HECTO_PASCAL_PER_L_PER_SEC:
        case NOM_DIM_KILO_PASCAL_PER_L_PER_SEC:
        case NOM_DIM_MILLI_L_PER_X_PASCAL:
        case NOM_DIM_MILLI_L_PER_HECTO_PASCAL:
        case NOM_DIM_MILLI_L_PER_KILO_PASCAL:
        case NOM_DIM_MM_HG_PER_X_L_PER_SEC:
        default:
            return "PHILIPS_"+unit.name();
        }
    }
}
