/**
 * @file    dim_rtsa.idl
 * @author  WMS
 * @date    AUG 2012
 * @brief   Define objects for Real Time Sample Array.
 *
 * @see ISO/IEEE 11073-10201 Health informatics - Point-of-care medical device
 * communication - Part 10201: Domain information model
 *
 * DocBox Inc, www.docboxinc.com. All rights reserved.
 */
//=============================================================================
//@copy #pragma once
#ifndef  DIM_RTSA_H_
#define  DIM_RTSA_H_

#include <dim_base_types.idl>

//=============================================================================
/**
 * Sample Array Object
 * The Sample Array object is the base for metrics that have a graphical, curve
 * type presentation and, therefore, have their observation values reported as
 * arrays of data points by communicating systems.
 */

struct SaObsValue
{
  OIDType  metric_id;  /// from VMO::Type or Metric-Id-Partition partition
  MeasurementStatus state;
  OIDType  unit_code;
  sequence <FLOATType,MAXARRAYSIZE_SAOBSVAL> array;
};

//=============================================================================
/**
 * Real Time Sample Array object
 * The Real Time Sample Array object is a sample array that represents a
 * real-time continuous waveform.
 */
struct DIMT_RealTimeSA
{
  /// Universal Device ID
  OCTETSTRING  udi[MAXSTRSIZE_UDI];
  MetricStatus  metric_status;
  sequence<SaObsValue,MAX_COMPOUND_NUOBSVALS>  compound_sa_nu_obs_value;
  /// Time of first sample observation.
  AbsoluteTime absolute_timestamp;

};

#endif // DIM_RTSA_H_
