#ifndef  DIM_NUOBS_VALUE_H_
#define  DIM_NUOBS_VALUE_H_

/**
 * @file    dim_nu_obs_value.idl
 * @author  WMS
 * @brief   Define objects for nu obs value.
 */
//=============================================================================


#include <org/mdpnp/types/denormalized/dim_base_types.idl>
//#include "dim_base_types.idl"

//=============================================================================
/*
 * Numeric object
 * The Numeric object represents numerical measurements and status information,
 * e.g., amplitude measures, counters.
 *
 * Example: A heart rate measurement is represented by a Numeric object.
 *
 *  NOTE: A compound Numeric object is defined as an efficient model, for
 * example, for arterial blood pressure, which usually has three associated
 * values (i.e., systolic, diastolic, mean). The availability of multiple
 * values in a single Numeric (or other Metric) object can be indicated in
 * special structure attribute in the Metric object.
 */

module org {
	module mdpnp {
			module types {
				module denormalized {

/**
 * Numeric Observed Value
 *
 * The Numeric Observed Value represents the (measured) value, state and
 * identification data.
 */
struct NuObsValue
{
  DIMHANDLE dimhandle;  /// 11073 name is handle, renamed to avoid conflict
  OIDType   metric_id;  /// from VMO::Type or Metric-Id-Partition partition
  MeasurementStatus state;
  OIDType   unit_code;
  FLOATType value;
};

const long NUOBSVALUE_SEQUENCE_MAX_LENGTH = 32;

/**
 * Observed value for compound numerics
 */
struct NuObsValueCmp
{
  sequence <NuObsValue, NUOBSVALUE_SEQUENCE_MAX_LENGTH> values;
};

/**
 * Numeric data type object
 */
struct DIMT_NumericObsVal
{
  /// Universal Device ID
  CHARSTRING   udi[MAXSTRSIZE_UDI];

  NuObsValueCmp compound_nu_obs_value;

  /// Time of observation.
  AbsoluteTime absolute_timestamp;

};
};
};
};
};
#endif
